name: Publish Python Distribution to PyPI

on:
  release:
    types: [published]

jobs:
  build:
    name: Build Distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install Dependencies and Build
      run: |
        python3 -m venv venv
        . venv/bin/activate
        pip install -U pip setuptools wheel build
        python -m build
    - name: Store Distribution Packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: >-
      Publish Python Distribution to PyPI
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/tpux
    permissions:
      id-token: write
    steps:
    - name: Download Distribution Packages
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
